In [24]:
import pandas as pd
import numpy as np

In [2]:
a = ['red', 'green', 'white']
b = ['blue', 'pink']
c = ['black']

In [5]:
ds = pd.Series([a, b, c])
ds

0    [red, green, white]
1           [blue, pink]
2                [black]
dtype: object

In [9]:
ds = pd.Series([a, b, c])
ds = ds.apply(pd.Series).stack().reset_index(drop=True)
ds

0      red
1    green
2    white
3     blue
4     pink
5    black
dtype: object

In [11]:
#Write a Pandas program to add some data to an existing Series.
ds = pd.Series(['100', '200', '300', 'python', '400.12'])
ds

0       100
1       200
2       300
3    python
4    400.12
dtype: object

In [13]:
ds1 = ds.append(pd.Series(['500', 'php']))
ds1

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9228\2425604350.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ds1 = ds.append(pd.Series(['500', 'php']))


0       100
1       200
2       300
3    python
4    400.12
0       500
1       php
dtype: object

In [14]:
# program to create a subset of a given series based on value and condition.
ds = pd.Series([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ds

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [16]:
n = 6
new_s = ds[ds<n]
new_s

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

In [20]:
#program to change the order of index of a given series.
ds = pd.Series([1, 2, 3, 4, 5, 6, 7], index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])
ds

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [21]:
ds = ds.reindex(index=['b', 'a', 'c', 'f', 'e', 'd', 'g'])
ds

b    2
a    1
c    3
f    6
e    5
d    4
g    7
dtype: int64

In [22]:
#program to get the items of a given series not present in another given series.
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
ds = sr1[~sr1.isin(sr2)]
ds

0    1
2    3
4    5
dtype: int64

In [26]:
#program to get the items which are not common of two given series.
sr11 = pd.Series(np.union1d(sr1,sr2))
sr12 = pd.Series(np.intersect1d(sr1, sr2))
ds = sr11[~sr11.isin(sr12)]
ds

0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64

In [29]:
#program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.
num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))
num_series

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

In [30]:
result = np.percentile(num_series, q=[0, 25, 50, 75,100])
result

array([ 3.00093811,  8.09463867, 10.23353705, 12.21537733, 14.61214321])

In [31]:
#alculate the frequency counts of each unique value of a given series.

series = pd.Series(np.random.randint(10, size=40))
series

0     0
1     5
2     5
3     1
4     4
5     6
6     7
7     0
8     5
9     0
10    1
11    9
12    6
13    7
14    5
15    3
16    4
17    0
18    7
19    0
20    8
21    3
22    4
23    4
24    4
25    1
26    5
27    7
28    9
29    3
30    4
31    0
32    7
33    7
34    7
35    2
36    5
37    1
38    1
39    4
dtype: int32

In [32]:
series.value_counts()

4    7
7    7
0    6
5    6
1    5
3    3
6    2
9    2
8    1
2    1
dtype: int64

In [33]:
#Pandas program to find the index of the first occurrence of the smallest and largest value of a given series. 
ds = pd.Series([1,3,7,12,88,23,3,1,9,0])
ds

0     1
1     3
2     7
3    12
4    88
5    23
6     3
7     1
8     9
9     0
dtype: int64

In [34]:
ds.idxmin()

9

In [35]:
ds.idxmax()

4

In [36]:
#Pandas program to check the equality of two given series.
# 0 1
# 1 8
# 2 7
# 3 5
# 4 6
# 5 5
# 6 3
# 7 4
# 8 7
# 9 1
ds1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
ds2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
ds1 == ds2

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool

In [43]:
#Pandas program to stack two given series vertically and horizontally
a = pd.Series(range(10))
b = pd.Series(list('pqrstuvwxyz'))
a.append(b)
df = pd.concat([a, b], axis=1)
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_9228\1683322154.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  a.append(b)


0  1
0   0.0  p
1   1.0  q
2   2.0  r
3   3.0  s
4   4.0  t
5   5.0  u
6   6.0  v
7   7.0  w
8   8.0  x
9   9.0  y
10  NaN  z

In [44]:
#program to convert given series into a dataframe with its index as another column on the dataframe.
char_list = list('ABCDEFGH')
char_list

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [47]:
np_ser = np.arange(8)
np_ser

array([0, 1, 2, 3, 4, 5, 6, 7])

In [48]:
df = dict(zip(char_list, np_ser))

In [49]:
df

{'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7}

In [50]:
ds = pd.Series(df)

In [51]:
ds

A    0
B    1
C    2
D    3
E    4
F    5
G    6
H    7
dtype: int32

In [53]:
df1 = ds.to_frame().reset_index()

In [54]:
df1

index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4
5     F  5
6     G  6
7     H  7

In [55]:
# program convert the first and last character of each word to upper case in each word of a given series. 

ds = pd.Series(["php", 'java', 'python', 'c#'])
ds

0       php
1      java
2    python
3        c#
dtype: object

In [60]:
ds.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())

0       PhP
1      JavA
2    PythoN
3        C#
dtype: object

In [3]:
import pandas as pd
import numpy as np

In [2]:

#Write a Pandas program to display most frequent value in a given series and replace everything else as ‘Other’ in the series.

In [5]:
ds = pd.Series(np.random.randint(1, 5, size=15))
ds

0     2
1     1
2     3
3     2
4     3
5     1
6     4
7     3
8     2
9     3
10    2
11    4
12    4
13    3
14    2
dtype: int32

In [6]:
ds.value_counts()

2    5
3    5
4    3
1    2
dtype: int64

In [7]:
result = ds[~ds.isin(ds.value_counts().index[:1])] = 'Other'
result

'Other'

In [8]:
ds

0         2
1     Other
2     Other
3         2
4     Other
5     Other
6     Other
7     Other
8         2
9     Other
10        2
11    Other
12    Other
13    Other
14        2
dtype: object

In [17]:
#Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.
ds1 = pd.Series(np.random.randint(10, 20, 9))
ds1

0    17
1    16
2    15
3    10
4    17
5    12
6    18
7    17
8    11
dtype: int32

In [22]:
ds1[ds1%5 == 0]

2    15
3    10
dtype: int32

In [18]:
result = np.where(ds1%5 == 0)

In [19]:
result

(array([2, 3], dtype=int64),)

In [23]:
#Write a Pandas program to extract items at given positions of a given series.
ds2 = pd.Series(list('0235689745896'))
ds2

0     0
1     2
2     3
3     5
4     6
5     8
6     9
7     7
8     4
9     5
10    8
11    9
12    6
dtype: object

In [24]:
element_pos = ['2', '5', '7', '0']
ds2.take(element_pos)

2    3
5    8
7    7
0    0
dtype: object

In [29]:
#Write a Pandas program to get the positions of items of a given series in another given series.
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
print(series1)
print(series2)

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0     1
1     3
2     5
3     7
4    10
dtype: int64


In [30]:
result = [pd.Index(series1).get_loc(i) for i in series2]
result

[0, 2, 4, 6, 9]

In [38]:
# Write a Pandas program to filter words from a given series that contain atleast two vowels. 

from collections import Counter
 
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
result = color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)

In [41]:
color_series[result]

1     Green
2    Orange
4    Yellow
5     White
dtype: object

In [43]:
color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)

0    False
1     True
2     True
3    False
4     True
5     True
dtype: bool