In [1]:
import pandas as pd
import numpy as np

In [2]:
ds = pd.Series([1, 2, 3, 4, 5, 6])
ds

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [3]:
type(ds)


pandas.core.series.Series

In [4]:
ds1 = ds.tolist()
ds1

[1, 2, 3, 4, 5, 6]

In [5]:
type(ds1)

list

In [6]:
dss1 = pd.Series([2, 4, 6, 8, 10])
dss2 = pd.Series([1, 3, 5, 7, 9])

In [7]:
dss1 + dss2

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [8]:
dss1 -dss2

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [9]:
dss1 * dss2

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [10]:
dss1 / dss2

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [11]:
dss1 == dss2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [12]:
dss1 > dss2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [13]:
dss1 < dss2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [14]:
d = {'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
ds = pd.Series(d)

In [15]:
ds

a    100
b    200
c    300
d    400
e    800
dtype: int64

In [16]:
arr = np.array([10, 20 ,30, 40, 50])
ds = pd.Series(arr)
ds

0    10
1    20
2    30
3    40
4    50
dtype: int32

In [17]:
sr = pd.Series(['100', '200', '300', 'python', '400.12'])
sr

0       100
1       200
2       300
3    python
4    400.12
dtype: object

In [18]:
pd.to_numeric(sr, errors = 'coerce')

0    100.00
1    200.00
2    300.00
3       NaN
4    400.12
dtype: float64

In [19]:
d1 = {'col1':[1 ,2, 3, 4, 5], 'col2': [7, 8, 9, 10, 11], 'col3': [12, 13, 14, 15, 16]}
ds = pd.DataFrame(d1)
ds

col1  col2  col3
0     1     7    12
1     2     8    13
2     3     9    14
3     4    10    15
4     5    11    16

In [20]:
type(ds)

pandas.core.frame.DataFrame

In [21]:
ds['col1']

0    1
1    2
2    3
3    4
4    5
Name: col1, dtype: int64

In [22]:
type(ds['col1'])

pandas.core.series.Series

In [23]:
sr = pd.Series(['100', '200', '300', 'python', '400.12'])
arr = np.array(sr.tolist())
arr

array(['100', '200', '300', 'python', '400.12'], dtype='<U6')

In [24]:
a = [10, 20, 30, 40]
b = [50, 60]
c = [70]
ds = pd.Series([a, b, c])
ds

0    [10, 20, 30, 40]
1            [50, 60]
2                [70]
dtype: object

In [25]:
ds.apply(pd.Series).stack().reset_index(drop=True)

0    10.0
1    20.0
2    30.0
3    40.0
4    50.0
5    60.0
6    70.0
dtype: float64

In [26]:
sr

0       100
1       200
2       300
3    python
4    400.12
dtype: object

In [27]:
sr.sort_values()

0       100
1       200
2       300
4    400.12
3    python
dtype: object

In [28]:
sr

0       100
1       200
2       300
3    python
4    400.12
dtype: object

In [29]:
sr.append(pd.Series(['500', 'php']))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10012\2489432320.py:1: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sr.append(pd.Series(['500', 'php']))


0       100
1       200
2       300
3    python
4    400.12
0       500
1       php
dtype: object

In [30]:
sr1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
sr1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [31]:
n = 6
sr1[sr1<n]

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [32]:
sr2 = pd.Series([1 ,2 ,3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
sr2

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [33]:
sr2.reindex(index=['b', 'c', 'a','d', 'e'])

b    2
c    3
a    1
d    4
e    5
dtype: int64

In [34]:
sr = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 5, 3])
sr

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64

In [35]:
sr.mean()

4.818181818181818

In [36]:
sr.std()

2.522624895547565

In [37]:
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])
sr1[~sr1.isin(sr2)]

0    1
2    3
4    5
dtype: int64

In [38]:
sr11 = np.union1d(sr1, sr2)
sr11

array([ 1,  2,  3,  4,  5,  6,  8, 10], dtype=int64)

In [39]:
sr12 = np.intersect1d(sr1, sr2)

In [40]:
sr12

array([2, 4], dtype=int64)

In [41]:
result = sr11[~sr11.isin(sr12)]

AttributeError: 'numpy.ndarray' object has no attribute 'isin'

In [42]:
np_sr = np.random.RandomState(100)
np_sr

RandomState(MT19937) at 0x1ED26283840

In [43]:
sr = pd.Series(np_sr.normal(10,4,20))
sr

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64

In [44]:
np.percentile(sr, q=[25, 50, 75, 100])

array([ 8.09463867, 10.23353705, 12.21537733, 14.61214321])

In [45]:
num_ser = pd.Series(np.random.randint(4, 10, 20))
num_ser

0     7
1     5
2     6
3     6
4     8
5     4
6     4
7     8
8     4
9     5
10    7
11    8
12    4
13    4
14    8
15    9
16    6
17    4
18    6
19    4
dtype: int32

In [46]:
sr = pd.Series(np.random.randint(10, size=40))
sr

0     4
1     9
2     0
3     3
4     7
5     8
6     5
7     3
8     9
9     7
10    0
11    7
12    2
13    5
14    9
15    6
16    6
17    2
18    7
19    6
20    6
21    9
22    9
23    7
24    7
25    7
26    1
27    6
28    4
29    8
30    5
31    8
32    3
33    3
34    3
35    5
36    6
37    2
38    9
39    9
dtype: int32

In [48]:
sr.value_counts()

3    4
4    3
8    2
5    2
6    2
9    1
1    1
dtype: int64

In [49]:
sr = pd.Series(np.random.randint(10, size=15))
sr

0     4
1     8
2     8
3     9
4     1
5     9
6     5
7     0
8     6
9     2
10    9
11    5
12    9
13    5
14    4
dtype: int32

In [50]:
sr.value_counts()

9    4
5    3
4    2
8    2
1    1
0    1
6    1
2    1
dtype: int64

In [51]:
(sr.value_counts().index[:1])

Int64Index([9], dtype='int64')

In [52]:
result = sr[~sr.isin(sr.value_counts().index[:1])]='other'

In [53]:
sr

0     other
1     other
2     other
3         9
4     other
5         9
6     other
7     other
8     other
9     other
10        9
11    other
12        9
13    other
14    other
dtype: object

In [54]:
sr = pd.Series(np.random.randint(1, 10, 10))

In [55]:
sr

0    8
1    4
2    3
3    6
4    9
5    5
6    5
7    2
8    8
9    4
dtype: int32

In [56]:
np.where(sr%5 == 0)

(array([5, 6], dtype=int64),)

In [57]:
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 10])
x = [pd.Index(series1).get_loc(i) for i in series2]

In [64]:
x = [pd.Index(series1).get_loc(i) for i in series2]

In [65]:
x

[0, 2, 4, 6, 9]

In [66]:
sr= pd.Series(['php', 'java','python', 'c#'])
sr

0       php
1      java
2    python
3        c#
dtype: object

In [67]:
sr.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())

0       PhP
1      JavA
2    PythoN
3        C#
dtype: object

In [68]:
sr.apply(len)

0    3
1    4
2    6
3    2
dtype: int64

In [72]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', '2019-04-06T11:20'])
x = pd.to_datetime(date_series)
x

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

In [74]:
x.dt.day.tolist()

[1, 2, 7, 6, 12, 6]

In [76]:
x.dt.month.tolist()

[1, 10, 3, 5, 4, 4]

In [77]:
x.dt.year.tolist()

[2015, 2016, 2018, 2014, 2016, 2019]

In [78]:
x.dt.dayofyear.tolist()

[1, 276, 66, 126, 103, 96]

In [80]:
x.dt.weekofyear.tolist()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_10012\622999328.py:1: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  x.dt.weekofyear.tolist()


[1, 39, 10, 19, 15, 14]

In [81]:
x.dt.weekday_name.tolist()

AttributeError: 'DatetimeProperties' object has no attribute 'weekday_name'

In [84]:
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White']) 
x = color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')])>=2 )

In [85]:
x

0    False
1     True
2     True
3    False
4     True
5     True
dtype: bool

In [86]:
color_series[x]

1     Green
2    Orange
4    Yellow
5     White
dtype: object

In [89]:
sr1 = pd.Series(range(8))
sr2 = pd.Series(list('qbcdefgh'))
len(sr1)

8

In [93]:
sr3 = pd.concat([sr1, sr2], axis=1)

In [94]:
sr3

0  1
0  0  q
1  1  b
2  2  c
3  3  d
4  4  e
5  5  f
6  6  g
7  7  h

In [95]:
li = list('abcdefgh')
arr = np.arange(8)
d = dict(zip(li, arr))
d

{'a': 0, 'b': 1, 'c': 2, 'd': 3, 'e': 4, 'f': 5, 'g': 6, 'h': 7}

In [101]:
ds = pd.Series(d)
ds

a    0
b    1
c    2
d    3
e    4
f    5
g    6
h    7
dtype: int32

In [104]:
ds.to_frame().reset_index()

index  0
0     a  0
1     b  1
2     c  2
3     d  3
4     e  4
5     f  5
6     g  6
7     h  7

In [98]:
x = pd.DataFrame(d, index=['r' + str(i) for i in range(4)])
x

a  b  c  d  e  f  g  h
r0  0  1  2  3  4  5  6  7
r1  0  1  2  3  4  5  6  7
r2  0  1  2  3  4  5  6  7
r3  0  1  2  3  4  5  6  7

In [99]:
pd.Series(x)

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().